name: Batch Deposit

on:
  workflow_dispatch:

env:
  ROLLUP_SCRIPT_ARGS: "0x86c7429247beba7ddd6e4361bcdfc0510b0b644131e2afb7e486375249a01802"
  GODWOKEN_WEB3_URL: "https://godwoken-betanet-v1.ckbapp.dev"
  CKB_RPC_URL: "https://testnet.ckb.dev"
  CKB_INDEXER_URL: "https://testnet.ckb.dev/indexer"

jobs:
  batch-deposit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: yarn install
      run: yarn && cd packages/cli && yarn
    - name: yarn run batch-deposit
      working-directory: packages/cli
      run: |
        yarn run batch-deposit \
          --lumos-config BETANET \
          -pk ../../.github/workflows/pks.json \
          --capacity 50100000000 \
          --n-derived-accounts 1000;
